### ISSUE TITLE
Enum filter

### ISSUE THREAD

**Issue by pperzyna** [elegantweb/sanitizer#12]
It would be nice to have an enum filter that could work similarly to the enum rule.

[https://laravel.com/docs/9.x/validation#rule-enum](https://laravel.com/docs/9.x/validation#rule-enum)

```
'price_type' => ['uppercase', new Enum(PriceType::class)],
```

**Comment by sharifzadesina** [comment]
Thanks, I'll try to implement this feature on my free time.
