### ISSUE TITLE
Update to support Laravel 10

### ISSUE THREAD

**Issue by lnxd** [elegantweb/sanitizer#15]
Just creating this issue so that you're aware that there's interest. We rely on your fantastic package for one of our projects, and we've updated to Laravel 10.

I can see that you have #14. Currently we're relying on a vcs setting which seems to work perfectly fine with the changes made in that PR (https://github.com/codea-au/sanitizer).

Keeping in mind that I don't think we've fully tested the code, the only thing that stands out to me as a glaring issue is that Laravel 10 doesn't work with PHP 8.0 so the test workflow needs to be rewritten, possibly to have a second matrix or the main `composer.json` file could remove support from old Laravel versions.

**Comment by sharifzadesina** [comment]
Hello,
Yes, I will update the package today or possibly tomorrow.

**Comment by lnxd** [comment]
Awesome, thank you!

**Comment by onlime** [comment]
just to let you know I have tested Laravel Shift's #14, confirming it working

**Comment by sharifzadesina** [comment]
A new version has been released. Thank you 🌹

**Comment by onlime** [comment]
> A new version has been released. Thank you 🌹

Great, thanks a lot!

One more thing though, that needs to be fixed: the package does not seem to get auto-updated on Packagist https://packagist.org/packages/elegantweb/sanitizer - no v2.1.0 there yet.
