### ISSUE TITLE
Problem with 'extend' method

### ISSUE THREAD

**Issue by luizdevs** [elegantweb/sanitizer#16]
I have problems using the 'extend' method in Laravel 10.

![image](https://user-images.githubusercontent.com/10924666/222934302-693432ab-48f1-4e6c-b3de-760be0b9b8c7.png)

I added the extension method in the AppServiceProvider, and the intelephense cannot identify the package

![image](https://user-images.githubusercontent.com/10924666/222934315-ffd7c702-f60d-46bf-89f3-a427c825099e.png)

Am I doing something wrong?

**Comment by sharifzadesina** [comment]
Make sure package alias is successfully auto loaded by Laravel.
