### ISSUE TITLE
Add support for Laravel 11

### ISSUE THREAD

**Issue by adiramardiani** [elegantweb/sanitizer#19]
Currently laravel have version 11 on dev stage, and developer can try, can you add support for laravel 11

**Comment by sharifzadesina** [comment]
Hello,
I think we can wait for the official release. What is the rush for?

**Comment by adiramardiani** [comment]
Okay No problem

Currently we have tried the latest version of Laravel, it is better to try from the beginning before release regarding compatibility than later, so we know what are the major issues, currently they are dependencies that already support laravel 11, and other are still waiting for release

I'm not too rushed now, it's just that if some packages are ready also when they are released, it will be faster to migrate laravel 11

**Comment by sharifzadesina** [comment]
@adiramardiani I actively support this package, so in the case of Laravel 11 release, I will update the package ASAP. no worries bro.

**Comment by madhurasri** [comment]
@sharifzadesina Laravel 11 is officially released now. [https://laravel.com/docs/11.x/releases](https://laravel.com/docs/11.x/releases)

I'm waiting for the update of this package.

**Comment by sharifzadesina** [comment]
v2.2.0 is compatible with Laravel 11.
