### ISSUE TITLE
Suggestion: Lower your minimum required php version.

### ISSUE THREAD

**Issue by adm-bome** [elegantweb/sanitizer#3]
Is there a specific reason php 7.4 is required?
You drastically limited you package for usability.

Laravel 8 (latest) is set to php 7.3 minimum and so are the most packages.

If there is no specific requirement for the use of php 7.4...
I would suggest lowering the required minimum version version an add a test (git action) for both (7.3, 7.4) php versions.

**Comment by sharifzadesina** [comment]
@adm-bome Yes, codes are cleaner. I use some of PHP 7.4 features.

**Comment by Kwaadpepper** [comment]
Too bad I could have used this, but lots of production servers are limited to 7.3 .
