### ISSUE TITLE
[Feature Request] If string is empty return null

### ISSUE THREAD

**Issue by TimVanHerwijnen** [elegantweb/sanitizer#6]
Hello, 

It would be nice if empty strings would be returned as `null`.

I thought this could be done as a filter like this:
```
$sanitizer = new Sanitizer($row, [
    'value' => 'trim|digit|null',
]);
```

**Comment by sharifzadesina** [comment]
This can be useful.
I will try to work on it in my free time.
meanwhile, PRs are welcome.
