### ISSUE TITLE
[Feature Request] Default catch-all filter

### ISSUE THREAD

**Issue by kevinnivek** [elegantweb/sanitizer#9]
Instead of having to identify all requests and which filters to apply, it would be greatly helpful if we could have a default filter to apply if the string parameter is not present in the $filters array.

**Comment by sharifzadesina** [comment]
I personally prefer "explicit" methods, having a default filter for all string parameters is not explicit and requires detection of string parameters.
But you can have it using middlewares (like what Laravel already does) or you can automatically add filters using your base HTTP Request in Laravel.
